apiVersion: v2
name: test-equipment
description: An umbrella Helm chart so that Helm Charts of Test Equipment (SigGen and SpectrAna), SkySimCtl can be deployed to a kubernetes cluster
type: application
version: 22.0.1
appVersion: 22.0.1
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  # Tango
  - name: ska-tango-base
    version: 0.4.9 # Check latest version
    repository: https://artefact.skao.int/repository/helm-internal

  - name: ska-tango-util
    version: 0.4.10 # Check latest version
    repository: https://artefact.skao.int/repository/helm-internal

  # SKA Test Equipment
  - name: ska-ser-test-equipment
    version: 0.9.1 # check latest version
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-ser-test-equipment.enabled

  # TARANTA SUITE
  - name: ska-tango-taranta
    version: 2.9.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-tango-tangogql
    version: 1.3.10
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled

  # SKA Configuration Inspector API
  # Gitlab Location: https://gitlab.com/ska-telescope/ska-ser-config-inspector
  # Releases: https://gitlab.com/ska-telescope/ska-ser-config-inspector/-/releases
  - name: ska-ser-config-inspector
    version: 0.2.3 # check latest version
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-ser-config-inspector.enabled
