variables:
  GIT_SUBMODULE_STRATEGY: recursive

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - when: always

stages:
  - verify-test-equipment
  - test-equipment-setup

include:
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/docs.gitlab-ci.yml"
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/finaliser.gitlab-ci.yml"
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/helm-chart.gitlab-ci.yml"
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/changelog.gitlab-ci.yml"

  - local: .gitlab/ci/.jobs.yaml
  - local: .gitlab/ci/.rules.yaml
  - local: .gitlab/ci/file-browser/.pipeline.yaml
  - local: .gitlab/ci/test-equipment/.pipeline.yaml

