variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - verify-test-equipment
  - lint
  - build
  - test
  - deploy
  - integration
  - staging
  - join-reports
  - pages
  - publish
  - scan

include:
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/docs.gitlab-ci.yml"
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/finaliser.gitlab-ci.yml"
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/helm-chart.gitlab-ci.yml"
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/changelog.gitlab-ci.yml"

  - local: .gitlab/ci/.jobs.yaml
  - local: .gitlab/ci/.rules.yaml
  - local: .gitlab/ci/file-browser/.pipeline.yaml
  - local: .gitlab/ci/test-equipment/.pipeline.yaml

