---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "fileBrowser.labels" . | nindent 4 }}
  name: {{ .Values.service.name }}
spec:
  externalName: {{ .Values.service.name }}
  ports:
  - name: {{ .Values.service.name }}
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    {{- if eq .Values.env.type "dev"  }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    {{- include "fileBrowser.selectorLabels" . | nindent 4 }}
  type: {{ include "fileBrowser.serviceType" . }}
