apiVersion: v2
name: ska-mid-itf-environments-test-equipment-verification
description: An umbrella Helm chart for verifying Helm Charts of Test Equipment Tango Device Servers at the Mid ITF
type: application
version: 26.2.0-dev
appVersion: 26.2.0-dev
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  # Tango
  - name: ska-tango-base
    version: 0.4.18 # Check latest version
    repository: https://artefact.skao.int/repository/helm-internal

  - name: ska-tango-util
    version: 0.4.18 # Check latest version
    repository: https://artefact.skao.int/repository/helm-internal

  # SKA Test Equipment
  - name: ska-ser-test-equipment
    # check latest version
    # version: 0.9.1-dev.c9943106d
    version: 0.9.1
    repository: https://artefact.skao.int/repository/helm-internal
    # repository: https://gitlab.com/api/v4/projects/31506252/packages/helm/dev
    alias: test-equipment
    condition: test-equipment.enabled

  # TARANTA SUITE
  - name: ska-tango-taranta
    version: 2.14.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-taranta.enabled
  - name: ska-tango-tangogql-ariadne
    version: 1.0.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-taranta.enabled
    alias: tangogql

