global:
  facility: mid-itf
  use_aws: true
  sub-system:
    ska-tango-base:
      enabled: false

ska-tango-base:
  itango:
    enabled: true
  tangodb:
    use_pv: true

test-equipment:
  legacy_compatibility: true
  enabled: true
  simulators:
    enabled: false
  deviceServers:
    progattenuator:
      devices:
        []
        # - name: rc1dat800030
        #   model: RC1DAT800030
        #   host: 10.165.3.6
        #   port: 45451
        #   protocol: telnet
        #   logging_level_default: 5
    awgvisa:
      devices:
        - name: awg5208i
          model: AWG5208I
          host: 10.165.3.3
          port: 4000
          protocol: tcp
          logging_level_default: 5
    oscilloscope:
      devices:
        - name: mso64b
          model: MSO64B
          host: 10.165.3.2
          port: 4000
          protocol: tcp
          logging_level_default: 5
    signalgenerator:
      devices:
        []
        # - name: smb100a
        #   model: SMB100A
        #   host: 10.165.3.1
        #   port: 5025
        #   resources:
        #     limits:
        #       skao.int/signal-generator-01: "1"
    sp6t:
      devices: []
    spdt:
      devices: []
    spectrumanalyser:
      devices: []
    spectrumanalyseranritsu:
      devices:
        []
        # - name: ms2090a
        #   model: MS2090A
        #   host: 10.165.3.4
        #   port: 9001
        #   protocol: tcp
        #   logging_level_default: 5

# TARANTA SUITE
ska-taranta:
  enabled: true
  ingress:
    enabled: true
    nginx: true
    # hostname: k8s.stfc.skao.int
  tangogql:
    replicas: 1
    resources:
      requests:
        cpu: 600m # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem

ska-tango-tangogql:
  ska-tango-base:
    enabled: false
